// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Infrastructure.Databass;

namespace Reservation.Infrastructure.Databass.Migrations
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20210723210942_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Reservation.Domain.ReservationRequests.ReservationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("State");

                    b.Property<Guid>("_tableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TableId");

                    b.Property<TimeSpan>("_visitingTime")
                        .HasColumnType("time")
                        .HasColumnName("VisitingTime");

                    b.HasKey("Id");

                    b.HasIndex("_tableId");

                    b.ToTable("ReservationRequests", "reservation");
                });

            modelBuilder.Entity("Reservation.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", "reservation");
                });

            modelBuilder.Entity("Reservation.Domain.Tables.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_restaurantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RestaurantId");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("_restaurantId");

                    b.ToTable("Tables", "reservation");
                });

            modelBuilder.Entity("Reservation.Domain.ReservationRequests.ReservationRequest", b =>
                {
                    b.HasOne("Reservation.Domain.Tables.Table", null)
                        .WithMany()
                        .HasForeignKey("_tableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation.Domain.Restaurants.Restaurant", b =>
                {
                    b.OwnsOne("Reservation.Domain.Restaurants.RestaurantAddress", "_address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("Reservation.Domain.Restaurants.RestaurantWorkingHours", "_workingHours", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("FinishTime")
                                .HasColumnType("time")
                                .HasColumnName("FinishWorkingAt");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("time")
                                .HasColumnName("StartWorkingAt");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("_address")
                        .IsRequired();

                    b.Navigation("_workingHours")
                        .IsRequired();
                });

            modelBuilder.Entity("Reservation.Domain.Tables.Table", b =>
                {
                    b.HasOne("Reservation.Domain.Restaurants.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("_restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Reservation.Domain.Tables.NumberOfSeats", "NumberOfSeats", b1 =>
                        {
                            b1.Property<Guid>("TableId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("_numberOfSeats")
                                .HasColumnType("tinyint")
                                .HasColumnName("NumberOfSeats");

                            b1.HasKey("TableId");

                            b1.ToTable("Tables");

                            b1.WithOwner()
                                .HasForeignKey("TableId");
                        });

                    b.Navigation("NumberOfSeats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
